### ISSUE TITLE
Doesn't work on time out dialogue

### ISSUE THREAD

**Issue by jhubb-io** [born05/craft-twofactorauthentication#11]
When the time out dialogue appears asking to reenter your password there is no way to enter the 2FA code again so although the password is correct and the dialogue disappears to show the CP again, the user is not actually logged in. A click to another page then redirects to the log in page.

**Comment by roelvanhintum** [comment]
Good point. It would be nice if it would show this after the login, or allow the user to continue.

Maybe add an extra config setting to let 2FA stay alive longer than the login itself. For example, login each day, 2FA once a week. Any thoughts on this?

**Comment by olets** [comment]
Something like that makes sense to me, and is familiar from other 2FA systems. Every week seems like a lot. I'm not finding documentation for Github or Google, but my guess is they prompt once a month?

**Comment by roelvanhintum** [comment]
@olets Both Github and Google ask you every time you login, but they allow you to stay logged in for a really long time. I hope to get things working with the dialog, but i'm afraid it will be a redirect to the verification page.

When another call is done after login, but before verification, the plugin logs the user out. When craft allows hooking further into the core this isn't needed anymore. see: https://github.com/craftcms/cms/issues/1471#issuecomment-402385051

**Comment by roelvanhintum** [comment]
Did some research, but Craft's AuthManager.js (which triggers the modal) doesn't throw any events when showing or hiding the modal. For now it's not possible to hook into this logic. Hopefully Craft will allow something like this in the future.

**Comment by weotch** [comment]
It appears to me that this dialog appears after 2min.  I'm not sure what setting controls this, though.

**Comment by roelvanhintum** [comment]
@weotch it is Craft getting session info, but the 2fa plugin logs out when a not allowed call is done before entering your 2fa code. I don't know if I can allow the session info call by default without causing any security vulnerabilities.
Path: `/index.php?p=admin/actions/users/session-info&dontExtendSession=1`

**Comment by goraxan** [comment]
@roelvanhintum pointed me to the right direction. The problem is that `/index.php?p=admin/actions/users/session-info&dontExtendSession=1` is not in the whitelisted actions of this plugin, so after calling it for the first time you are silently [logged out](https://github.com/born05/craft-twofactorauthentication/blob/craft-3.1/src/services/Request.php#L35). 
This is because this plugin [only support the old action](https://github.com/born05/craft-twofactorauthentication/blob/craft-3.1/src/services/Request.php#L196) `/users/get-remaining-session-time`  which apparently is not called anymore from craft 3.4 according to https://github.com/craftcms/cms/issues/5392

The fix consists on adding this line into the isCraftSpecialRequests() method `$actionSegs === ['users', 'session-info']`

**Comment by roelvanhintum** [comment]
@goraxan thanks! I've just released this in 2.7.4
