### ISSUE TITLE
Issuer must not contain a colon

### ISSUE THREAD

**Issue by supercooljames** [born05/craft-twofactorauthentication#75]
I've installed the plugin, but I'm getting the following error message.

I've not configure or added any users. I've tried a combination of options in the config file to no avail.

Am I missing something obvious?

![image](https://user-images.githubusercontent.com/169197/226440385-7f942b8b-80d3-4921-80ed-b2b8db567f69.png)

```
Assert\InvalidArgumentException
Issuer must not contain a colon
```

(Craft: 3.7)

Any help much appreciated

**Comment by jamie-s-white** [comment]
This is happening because the plugin is using the variable:

Craft::$app->getSystemName()

Which in our case is returning a system name variable which contains a colon character.

It seems that the problem is that the assumption with this plugin is that the Craft System Name only contains alphanumeric characters, which isn't necessiarily true, and that the fix for this bug would be to sanitise the system name before using it for the issuer parameter?
