### ISSUE TITLE
Only require 2FA once per day.

### ISSUE THREAD

**Issue by ben-honcho** [born05/craft-twofactorauthentication#99]
Hi Roel,

Is there a way to only require a user to use the 2FA once a day? 

After using it once, it will just be a regular login for 24 hours?

Kind regards,
Ben

**Comment by roelvanhintum** [comment]
Hi @ben-honcho, the 2fa plugin stores the validation in the session. When the session of craft cms itself ends, the user has to go through 2fa again.

I prefer to keep 2fa required after each login, it would be a security risk otherwise. I would increase the session duration of craft, if users have to login too many times a day.

**Comment by ben-honcho** [comment]
Thanks Roel 👍
